### ISSUE TITLE
[FR] [partial bug?] RUST interactivity

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/ScavStation#392]
Would love it if the ship's RUST had a little more interactivity available to it. I know it can make metals depending on what you fuse, but a slightly more viable method of inserting and extracting would be great. (Also, I'm pretty sure the insertion part is still broken. I haven't managed to insert helium into it. (Or the atmo system, for that matter))

**Comment by MadCowKastor** [comment]
Personally I think all inserting should be handled by the injectors as realistically fusion requires a near-vacuum environment, But those do need a rework. They should really be gas based rather than rod based. Fuel rod injection is a fission thing. As for extraction that should be handled by new device as well. Matter shouldn't just disappear from the torus as it does now, a filter of some kind should have to actively remove it. Or perhaps that device instead being rolled into the functions of the RUST itself.

**Comment by MistakeNot4892** [comment]
Going to close this as a bit vague to be actionable, and possibly unneeded in view of the fuel rod composition changes on main Neb.
