### ISSUE TITLE
Ship controls sometimes don't work

### ISSUE THREAD

**Issue by Greenjoe12345** [ScavStation/ScavStation#543]
#### Description of issue
The ship's helm controls suddenly decided to not work, even when they should have been working, resulting in everyone dying a horrible death as the ship hit big space rocks

#### Difference between expected and actual behavior
It should have taken the inputs and stopped the ship?

#### Steps to reproduce
fly the ship around for a while with plenty of power to keep the thrusters going

#### Length of time in which bug has been known to occur

Not too sure, the controls have always been a bit funky since i've played here however.

#### Client version, Server revision & Game ID

client version: 513
8f68195a2cffda6fe7b8c34ec0750b0aea26d4db - dev - 2021-02-11
Game ID was the one before caz-cVwk

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/ScavStation/ScavStation/issues)

**Comment by MistakeNot4892** [comment]
So after some rigorous testing of flying around on Scav, I've concluded that this is due to turning on all of the engines. I think it might possibly be due to running all engines at once draining the atmos or the APC enough to trigger the automatic channel switch until the SMES refills the APC or the pumps refill the propellant pipe.
Either way, this is not quite a bug. If you only turn on 2-3 of the engines you get plenty of thrust and they don't conk out in the middle.
